touch/sec: Fix warning caused by not checking return value
sec_ts.c:1879:2: error: ignoring return value of function declared with
'warn_unused_result' attribute [-Werror,-Wunused-result]
      kfifo_out_peek(&debug_fifo, last_coord, kfifo_size(&debug_fifo));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I46f45e73156b5742a762054e9e70bad957d1b335